---
title: "Disease_Challenge_Filtering"
author: "Jacob Agerbo Rasmussen"
date: "4/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r setup chunk, include=FALSE}
### Phyloseq
library(phyloseq); packageVersion("phyloseq")
library(ggplot2); packageVersion("ggplot2")
library(vegan); packageVersion("vegan")
library(dplyr); packageVersion("dplyr")
library(cowplot); packageVersion("cowplot")
library(data.table); packageVersion("data.table")
library(car);packageVersion("car")
library(lme4);packageVersion("lme4")
library(RColorBrewer);packageVersion("RColorBrewer")
library(ggpubr)
library(rstatix)
library(decontam)
```
We use Phyloseq to organise our data for profiling the V3-V4 region of 16S rRNA gene, thank you @joey711.
```{r Import and arrange data for ASVs, message=FALSE}
ASVs <- read.csv("Curated_Table.csv", sep = ",", row.names = 1)
tax <- read.csv("Curated_Tax.csv", sep = ",", row.names = 1)
md <- read.csv("metadata.csv", sep = ",")

rownames(md) <- md$Sample_ID
md$quant_reading <- colSums(ASVs)

physeq <- phyloseq(otu_table(ASVs,taxa_are_rows=TRUE),
               tax_table(as.matrix(tax)),
               sample_data(md))
```

```{r Decontam, message=FALSE}
df <- as.data.frame(sample_data(physeq)) # Put sample_data into a ggplot-friendly data.frame
df$LibrarySize <- sample_sums(physeq)
df <- df[order(df$LibrarySize),]
df$Index <- seq(nrow(df))
ggplot(data=df, aes(x=Index, y=LibrarySize, color=Sample_Type)) + geom_point()
```
```{r Decontam, message=FALSE}
contamdf.freq <- isContaminant(physeq, method="frequency", conc="quant_reading")
head(contamdf.freq)

table(contamdf.freq$contaminant)

sample_data(physeq)$is.neg <- sample_data(physeq)$Sample_Type == "Blank"
contamdf.prev <- isContaminant(physeq, method="prevalence", neg="is.neg", threshold=0.1)
table(contamdf.prev$contaminant)


# Make phyloseq object of presence-absence in negative controls and true samples
ps.pa <- transform_sample_counts(physeq, function(abund) 1*(abund>0))
ps.pa.neg <- prune_samples(sample_data(ps.pa)$Sample_Type == "Blank", ps.pa)
ps.pa.pos <- prune_samples(sample_data(ps.pa)$Sample_Type != "Blank", ps.pa)
# Make data.frame of prevalence in positive and negative samples
df.pa <- data.frame(pa.pos=taxa_sums(ps.pa.pos), pa.neg=taxa_sums(ps.pa.neg),
                      contaminant=contamdf.prev$contaminant)
ggplot(data=df.pa, aes(x=pa.neg, y=pa.pos, color=contaminant)) + geom_point() +
  xlab("Prevalence (Negative Controls)") + ylab("Prevalence (True Samples)")
```

ASVs with same taxa were concatenated by genus level to remove redundancy

````{r}
ps.noncontam <- prune_taxa(!contamdf.prev$contaminant, physeq)
ps.noncontam
physeq
ps.noncontam.glom = tax_glom(ps.noncontam, "Genus")
```

```{r barplot stuff,message=FALSE}
ASV_table <- ps.noncontam.glom@otu_table@.Data
tax_table <- ps.noncontam.glom@tax_table@.Data



write.csv(ASV_table, "ASV_table_glom.csv")
write.csv(tax_table, "tax_table_glom.csv")
```
