---
title: "Immune_Expression_Yr_Challenge"
author: "Jacob Agerbo Rasmussen"
date: "6/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load dependecies, warning=FALSE, tidy=TRUE, message=FALSE}
library(ggplot2);packageVersion("ggplot2")
library(RColorBrewer);packageVersion("RColorBrewer")
library(ggpubr);packageVersion("ggpubr")
library(rstatix);packageVersion("rstatix")
library(cowplot);packageVersion("cowplot")
library(reshape2);packageVersion("reshape2")
library(knitr);packageVersion("knitr")
library(MASS);packageVersion("MASS")
library(caret);packageVersion("caret")
library(wesanderson);packageVersion("wesanderson")
library(psych);packageVersion("psych")
library(corrplot);packageVersion("corrplot")
library(readxl);packageVersion("readxl")
library(WGCNA)
library(ComplexHeatmap)
library(cluster)
library(igraph)
library(phyloseq)
library(dplyr)
library(scales)
```

## Including Plots

You can also embed plots, for example:

```{r load data, echo=FALSE}
md <- read.csv("Immune_gene_microbe_sample_info.csv")
immune <- read_xlsx("Immune_Expression_Data.xlsx", sheet = "R")

rownames(immune) <- immune$Sample
immune <- immune[,-c(1)]
immune_sub <- immune %>%
  select("C3","Cathelicidin 1","Cathelicidin 2","IFN g","IgM","IgT","IL-1b", "IL6", "IL-10","Lysozyme","SAA","TNFa")
#
## Remove mid gut samples from ASV and MD
md <- md[md$Gut.Section == "Distal Gut content",]
md$Group <- c(rep("A",40),rep("B",40),rep("C",40),rep("D",40))
```

```{r}
group_pal <- c("#ADDAB9", "#3B5D9C") 

stat.data <- cbind(md$Infection.Stage, md$Feed,md$Group,immune_sub)
rownames(stat.data) <- md$Sample
stat.data <- melt(stat.data)
colnames(stat.data) <- c("Infection","Feed","Group", "Variable", "Value")

Summary <- stat.data %>%
  mutate(Group2 =  paste0(Variable, "-", Group)) %>%
  group_by(Group2) %>%
  summarise(
    count = n(),
    mean = mean(Value, na.rm = TRUE),
    sd = sd(Value, na.rm = TRUE), 
  )

stat.test <- stat.data %>%
  group_by(Variable) %>%
  tukey_hsd(Value ~ Group)

nz.stat.data <- stat.data
nz.stat.data[is.na(nz.stat.data)] <- 0

oneway.anova.test <- nz.stat.data %>%
  group_by(Variable) %>%
  anova_test(Value ~ Infection*Feed)


stat.test <- stat.test %>%
  add_x_position(x = "Group", dodge = 0.8) %>%
  add_y_position()

## Make y axis more sensible

    # Create a box plot
plot = ggboxplot(
      stat.data, x = "Group", y = "Value", 
      color = "black",
      fill = "Infection", palette = group_pal,
      add = "jitter", shape = "Infection",
      outlier.shape = 8, order = c("A", "B", "C", "D"),
      size = 0.5,
      title = "")  + 
      stat_pvalue_manual(
        stat.test,  label = "{p.adj.signif}", tip.length = 0.045,
        step.group.by = "group1",
        step.increase = 0.0,
        position = "identity", 
        y.position = 0.5)

plot = plot + xlab("Test Groups") + #changing labels
  ylab("Gene Expression (2^-DCq)") + 
  facet_wrap(~Variable, nrow = 3) + 
  ylim(c(min(stat.data$Value), max(stat.data$Value))) +
  scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),
              labels = trans_format("log10", math_format(10^.x)))


```
```{r}
#pdf("Gene_Expression_analysis_real.pdf", height = 12, width = 16)
cowplot::plot_grid(plot, labels = 'AUTO')
#dev.off()
```
